### ISSUE TITLE
missing index.js

### ISSUE THREAD

**Issue by MorisR** [alaabashiyi/node-js-auto-complete#1]
the project should include a clear starting point ( a file that tells you where the project starts ) 
traditionally an "index.js" file is included in the root directory of the project (and sometimes even in directories like src/server) to indicate the starting point of the project/directory/etc..

the "main" field in the  ```package.json``` file should also reference that starting point file

https://github.com/alaabashiyi/node-js-auto-complete/blob/9c598f8cc92c29d2e8f151476c0390bda2513fc3/package.json#L5

**Comment by alaabashiyi** [comment]
Thanks for the note! fixed
