### ISSUE TITLE
unused variables

### ISSUE THREAD

**Issue by MorisR** [alaabashiyi/node-js-auto-complete#2]
https://github.com/alaabashiyi/node-js-auto-complete/blob/9c598f8cc92c29d2e8f151476c0390bda2513fc3/server/server.js#L5
https://github.com/alaabashiyi/node-js-auto-complete/blob/9c598f8cc92c29d2e8f151476c0390bda2513fc3/server/handlers/places.js#L3

**Comment by alaabashiyi** [comment]
Fixed.
