### ISSUE TITLE
unnecessary async function

### ISSUE THREAD

**Issue by MorisR** [alaabashiyi/node-js-auto-complete#3]
you're not using the await keyword with in the function before the promise

might as well remove the try/catch blocks and the async keyword because you only got a single promise,
it wouldn't affect the outcome

https://github.com/alaabashiyi/node-js-auto-complete/blob/9c598f8cc92c29d2e8f151476c0390bda2513fc3/server/handlers/axios-api.js#L3-L11

change it to 
```javascript
const getPlaces = (place) => { 
     return axios.get( ... )
}
```

**Comment by alaabashiyi** [comment]
True, I should have added await before the axios.get but I used  it in places as a promise anyway.
Fixed
