### ISSUE TITLE
places.js error handling

### ISSUE THREAD

**Issue by Karyum** [alaabashiyi/node-js-auto-complete#4]
in the catch you need to handle the error in case there is one

https://github.com/alaabashiyi/node-js-auto-complete/blob/master/server/handlers/places.js#L27-L29

places where you could reuse the `missingHandler`
https://github.com/alaabashiyi/node-js-auto-complete/blob/master/server/handlers/places.js#L19-L21

**Comment by alaabashiyi** [comment]
Thanks! fixed
