### ISSUE TITLE
spaces are invalid urls

### ISSUE THREAD

**Issue by MorisR** [alaabashiyi/node-js-auto-complete#5]
the following url's are invalid:
https://github.com/alaabashiyi/node-js-auto-complete/blob/9c598f8cc92c29d2e8f151476c0390bda2513fc3/server/tests/alltests.js#L29
https://github.com/alaabashiyi/node-js-auto-complete/blob/9c598f8cc92c29d2e8f151476c0390bda2513fc3/server/tests/alltests.js#L42
https://github.com/alaabashiyi/node-js-auto-complete/blob/9c598f8cc92c29d2e8f151476c0390bda2513fc3/server/tests/alltests.js#L56

you can use ```encodeURI()``` to resolve it

**Comment by alaabashiyi** [comment]
Fixed with encode + decode; correct me if I'm wrong
const benGurion = encodeURI("/getdata?name=ben gurion");
decodeURI(benGurion)

**Comment by MorisR** [comment]
you should only use the encodeURI, it's meant for api calls

use the decodeURI if you want to turn it back to string

**Comment by alaabashiyi** [comment]
Okay, so i just need to encode the URL and the server will decode it .
