### ISSUE TITLE
change these to actual if statements 

### ISSUE THREAD

**Issue by MorisR** [alaabashiyi/node-js-auto-complete#8]
by changing the "&&" and the "inline if" to actual if statements, the code would become more readable

https://github.com/alaabashiyi/node-js-auto-complete/blob/9c598f8cc92c29d2e8f151476c0390bda2513fc3/server/public/script.js#L70-L71

**Comment by alaabashiyi** [comment]
Done!
![image](https://user-images.githubusercontent.com/29834132/98869903-1eb9c300-247b-11eb-963e-8b60b30684a5.png)
